spring:
  jmx:
    enabled: true
  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: ${oAuth2IntrospectionUri}
          client-id: ${oAuth2ClientId}
          client-secret: ${oAuth2ClientSecret}
  application:
    name: micro-gateway-services-30ce3bf8-8e00-4498-81b9-740d4cb4e3f9
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-SOCGEN-GATEWAY, 1
        - AddResponseHeader=X-SOCGEN-UUID, 30ce3bf8-8e00-4498-81b9-740d4cb4e3f9
      routes:
        - id: _doctor_doctorType_
          uri: http://localhost:8080/
          predicates:
            - Path=/doctor/{doctorType}
          filters:
            - TokenRelay=
            - RemoveResponseHeader=X-Forwarded-For=
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST